
- hosts: localhost
  connection: local
  become: no

  vars:
    empties_list:
    - name: tw5
      url: https://tiddlywiki.com/empty.html

    - name: prerelease
      url: "{{ prerelease_empty }}"

    - name: classic
      url: https://classic.tiddlywiki.com/empty.html

    empties_dir: ../rails/tw_content/empties

  tasks:
  - name: Download empties
    get_url:
      url: "{{ item.url }}"
      dest: "{{ empties_dir }}/{{ item.name }}.html"
      mode: '0644'
    with_items: "{{ empties_list }}"
